data_dir: "../data"
metadata_dir: "../data/metadata" # stores PDF covers
host: "http://0.0.0.0" # exclude port for now
port: 5689
num_docs: 1000 # maximum number of Documents to index
return_docs: 10
debug: true # allow setting server/port from frontend directly
protocol: "http"

# see frontend/.streamlit/config.toml for additional frontend config
