version: "3.7"

services:
  frontend:
    build: frontend
    environment:
      - SERVER=searcher
      - DEBUG=False
    ports:
      - 8512:8512
    depends_on:
      - searcher
    volumes:
      - ./frontend:/workspace
      - ./data:/data
    restart: always

  searcher:
    build: searcher
    environment:
      - IN_DOCKER=True
    ports:
      - 5689:5689
    volumes:
      - ./data:/data
    restart: always
