version: "3.7"

services:
  frontend:
    build: frontend
    environment:
      - SERVER=backend
      - DEBUG=False
    ports:
      - 8512:8512
    depends_on:
      - backend
    volumes:
      - ./frontend:/workspace
      - ./data:/data
    restart: always

  backend:
    build: backend
    environment:
      - IN_DOCKER=True
    ports:
      - 5689:5689
    volumes:
      - ./data:/data
    restart: always
